version: '3.9'

services:
  mongo:
    image: mongo:6
    container_name: journaling-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build: .
    container_name: journaling-api
    depends_on:
      - mongo
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/journaling_db
      - OPENAI_API_KEY=sk-xxx
    volumes:
      - .:/app
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  mongo_data: